### ISSUE TITLE
[FR] Setting to choose between single-line and multi-line yaml

### ISSUE THREAD

**Issue by FeralFlora** [PKM-er/obsidian-zotlit#102]
I prefer single-line arrays for tags and such, but Obsidian-Zotero formats the yaml as multi-line lists. It would be great if this behavior could be adjusted in a setting.

**Comment by aidenlx** [comment]
this behavior is controlled by obsidian yaml stringify API, for which does not provide configuration. You might have to open FR in obsidian forum as well.

**Comment by aidenlx** [comment]
In v1.1.0-beta6, you can disable formatter in initial note render, check out the end of this chapter for details: https://zotlit.aidenlx.top/getting-started/basic-usage/template-config#note-properties-template
