### ISSUE TITLE
Uncaught (in promise) Error: Setting tab is not mounted

### ISSUE THREAD

**Issue by cs-mshah** [PKM-er/obsidian-zotlit#122]
This error comes when this plugin is used along with the settings search plugin.
![Screenshot from 2023-04-06 18-04-13](https://user-images.githubusercontent.com/56499208/230380165-5b5bbebb-b6e8-4323-8e5d-3fb75e41bf09.png)

**Comment by aidenlx** [comment]
The plug-in doesn't use regular setting items so it won't work with setting search plugin. I might add search feature inside the setting tab.
