### ISSUE TITLE
"Update Literature Notes" button doesn't update all fields

### ISSUE THREAD

**Issue by seisman** [PKM-er/obsidian-zotlit#124]
First of all, thanks a lot for this great plugin!

I followed this post (https://forum.obsidian.md/t/obsidian-zotero-import-templates/56901/2) and added the abstract to the note template by adding the following lines:
```
> [!abstract]- Abstract
><%= it.abstractNote %>
```
then I enabled the "Overwrite Existing Note" option.

Here are the steps I did:

1. Create a literature note, in which I can see the abstract and all annotations
2. Add one more annotation in Zotero PDF reader and click the "Update Literature Note" button in Obsidian. The annotations in the note are updated.
3. Modify the literature fields (abstract in my case) and click the "Update Literature Note" button in Obsidian. Nothing happens. The abstract in the note is NOT updated.
4. Restart Obsidian, and click the "Update Literature Note" button in Obsidian, now the abstract is updated correctly. (Sometimes restarting Obsidian is not enough. I think I have to restart both Obsidian and Zotero).

Is it because 

1. Zotero doesn't write the changes to the Zotero Database immediately after changing the literature fields? (This may not be true, because sometimes I don't restart Zotero and the abstract can be updated).
2. Obsidian only read the Zotero database once when starting Obsidian? (This may not true, because the annotations are updated correctly without restarting Obsidian).
3. Other possible causes?

**Comment by seisman** [comment]
Thanks! "Refresh Zotero Data" works as expected.

I already enabled the following setting, so I thought the database should be automatically refreshed.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/3974108/231633583-d73e5a31-bcb3-449b-9396-13c04b284201.png">

Feel free to close the issue if it's not a unexpected behavior.

**Comment by zhechenghu** [comment]
Good to hear it works! I found that the database refreshes right after an annotation is edited. But it still needs to manually refresh after the doc item property is changed.
