### ISSUE TITLE
Feature: custom link format for page link drag-n-drop in annotation view

### ISSUE THREAD

**Issue by aqwqq** [PKM-er/obsidian-zotlit#143]
When I put a citation link into the Markdown text, how can I get the effect below, automatically changing Page 1 to (Zhang et al., 2014, p. 1)? This will save a lot of time in the paper writing process.
![屏幕截图 2023-05-23 152732](https://github.com/aidenlx/obsidian-zotero/assets/129646056/57a4762d-f52d-4a86-aad6-7c9c83892dbc)

**Comment by MSBack** [comment]
Duplicate of #141.

**Comment by siainbuletin** [comment]
bump
