### ISSUE TITLE
Feature:Added the ability to identify note attachments

### ISSUE THREAD

**Issue by SimonJarry** [PKM-er/obsidian-zotlit#160]
Currently, there is too little information about readable fields in Zotero items. The customizable information is stored in the notes and read, so as to perform some retrieval and display operations in obsidian. 

If you have other methods, please let me know, imprudent gratitude！

**Comment by aidenlx** [comment]
Thanks for submitting this feature! To better understand and potentially implement it, could you please elaborate on the following:

1. Can you provide a detailed use case or scenario where this feature will be beneficial?
2. How do you envision the interaction between Zotero items and Obsidian with this new ability?
3. Are there specific fields in Zotero items that you are particularly interested in making more readable or customizable?
4. If possible, could you share a visual mock-up or flow diagram of how you see this feature working?

**Comment by SimonJarry** [comment]
Thanks for your reply！
Answer 1：Other user-defined information, such as notes, can be stored in the corresponding field, such as research overview.
Answer 2：Start by customizing additional field information in Zotero, similar to the title field. It is then displayed in Obsidian, followed by the inline fields. For example: AAA:: '{{additional field}}. Finally, other functions such as retrieval display can be performed.
Answer 3：After testing, only some of the fields in your script can be read. In addition, different field types have different information filling requirements. You can think of user-defined fields as user notes.
Answer 4：Sorry, I can't provide a flow chart. The following figure shows the functions of user-defined fields that can be implemented in other document management software. You know, I'm used to using Zotero, so I wanted to add this feature to make it easier for users to enter other information, rather than creating a new note store.
![image](https://github.com/PKM-er/obsidian-zotlit/assets/49628143/37ed0b8b-e598-4f34-bb83-8d87304dfce0)
