### ISSUE TITLE
Update to new Electron version to accommodate Obsidian 1.4 update

### ISSUE THREAD

**Issue by siainbuletin** [PKM-er/obsidian-zotlit#165]
With the new 1.4 update now available to the general public, the Electron installer has been updated and now the plugin will not work anymore.

**Comment by ArtemisFowl-san** [comment]
Same here

**Comment by AnthonyMcDougal** [comment]
This plugin is great! I would love to have it working again!

**Comment by aidenlx** [comment]
Can you post the screenshot of error message in latest installer? In macOS the binary still support the installer of 1.4.5
