### ISSUE TITLE
Feature Request: add field related to Collections

### ISSUE THREAD

**Issue by SeveNOlogy7** [PKM-er/obsidian-zotlit#176]
Hi,

Some people (like me) would use collections to organize papers in Zotero and would like to import their collection structure of an item into Obsidian note. However the plugin now does not provide fields related collections.

So may I suggest adding collection fields like:
- collections: collections where the entry is located
- collectionsPaths: full paths to the collections where the entry is located.

Many Thanks!

**Comment by machado-t** [comment]
This is very important for my use case as well.

**Comment by siainbuletin** [comment]
Perhaps a way to synchronise notes within Obsidian with the tag system in Zotero would be even better. I think about how I use a set of tags as UNREAD, CURRENT, READ and PAUSED and I do the same in Obsidian. Having them immediately show up as some sort of status would be really useful, though maybe the degree of separation would be really complicated. I don't know, I may just be riffing on an idea right now.

**Comment by machado-t** [comment]
[Other plugins](https://github.com/mgmeyers/obsidian-zotero-integration) are capable of fetching both tags and collections, so I expect this to be possible for this one as well.

**Comment by aidenlx** [comment]
It's available in v1.1.0 beta.8, check out here for usage: https://zotlit.aidenlx.top/how-to/template-cheatsheet#collection

**Comment by aidenlx** [comment]
> Perhaps a way to synchronise notes within Obsidian with the tag system in Zotero would be even better. I think about how I use a set of tags as UNREAD, CURRENT, READ and PAUSED and I do the same in Obsidian. Having them immediately show up as some sort of status would be really useful, though maybe the degree of separation would be really complicated. I don't know, I may just be riffing on an idea right now.

Maybe posting your idea about it in a dedicated [discussion](https://github.com/PKM-er/obsidian-zotlit/discussions/new?category=ideas) is a better idea :)

**Comment by FeralFlora** [comment]
> > Perhaps a way to synchronise notes within Obsidian with the tag system in Zotero would be even better. I think about how I use a set of tags as UNREAD, CURRENT, READ and PAUSED and I do the same in Obsidian. Having them immediately show up as some sort of status would be really useful, though maybe the degree of separation would be really complicated. I don't know, I may just be riffing on an idea right now.
> 
> Maybe posting your idea about it in a dedicated [discussion](https://github.com/PKM-er/obsidian-zotlit/discussions/new?category=ideas) is a better idea :) @siainbuletin

@siainbuletin Although this is off-topic for this issue, but since there is no discussion on this yet, I will write here: It should already be possible to do this with the new zt-field.eta template. Create a property called `status:` in the template, and then perhaps use `filter` or a conditional on `it.tags` to target only the tags that you represent statuses.
