### ISSUE TITLE
citekey problem and zotero search problem

### ISSUE THREAD

**Issue by fgarbicz** [PKM-er/obsidian-zotlit#180]
The citekey is not inserted into note when citation is added. Also the citation is not recognized, per the image (i changed the display template for citation to DOI)
![image](https://github.com/PKM-er/obsidian-zotlit/assets/65818371/ae361dc4-9426-4e16-a5ba-1b277f5e34ed)

Same goes with citation notes, citationkey is not displayed.

WIndows 11, Zotero6

**Comment by fgarbicz** [comment]
Started working when I disabled Zotero Integration and Zotero Bridge community plugins!

**Comment by aidenlx** [comment]
Can you confirm that the issue is caused by conflict with those plugins you've mentioned? I haven't test against those plugins before.

**Comment by fgarbicz** [comment]
Confirmed. Turning on either one of those two plugins results in ZotLit not working correctly.

**Comment by aidenlx** [comment]
closing this since it's caused by different handling of pandoc citekeys among plugins
