### ISSUE TITLE
收藏似乎无法识别

### ISSUE THREAD

**Issue by toorukt** [PKM-er/obsidian-zotlit#182]
首先感谢A大开发这么优秀的插件！！

听说最新的beta8版支持文献收藏夹了，
于是赶快试用了一下（期待已久的功能，再次感谢）。
然而发现不论是zotero7还是zotero6似乎都无法正确识别收藏的位置。

<img width="930" alt="スクリーンショット 2023-09-09 21 12 53" src="https://github.com/PKM-er/obsidian-zotlit/assets/92703225/d9a7386b-e596-4c4b-9eda-1cb82b0cb8f1">
如上图，可以看到这篇文献属于rumination这个收藏夹中，
然而在zotero里面查看属性时，识别到的collection为null。
<img width="299" alt="スクリーンショット 2023-09-09 21 15 29" src="https://github.com/PKM-er/obsidian-zotlit/assets/92703225/93941285-f5e3-4e8d-b118-01e272e220cc">

麻烦A大查看下是不是bug？
谢谢🙏

**Comment by SeveNOlogy7** [comment]
same here

**Comment by aidenlx** [comment]
beta9 应该可以用了

**Comment by toorukt** [comment]
感谢A大！🥹
beta9目前能正常识别了。
但是似乎功能上不支持复数收藏夹？

**Comment by aidenlx** [comment]
复数收藏夹是什么意思？

**Comment by toorukt** [comment]
就是某个文献同时属于多个同级收藏的情况。
比如最上面截图中，
如果把当前属于rumination的这篇文献添加到同级的scale收藏中的话，
似乎只能识别最后一次添加的scale，
而之前的rumination收藏会被覆盖。

**Comment by aidenlx** [comment]
beta10已经支持了，这里有用例：https://zotlit.aidenlx.top/zh-CN/how-to/template-cheatsheet#collection

**Comment by toorukt** [comment]
简直神速！！
这个插件真的是让研究生活便利了非常多，真的是感激不尽🙏
