### ISSUE TITLE
Can't create literature note without annotations

### ISSUE THREAD

**Issue by Kullenej** [PKM-er/obsidian-zotlit#184]
Hello and once again thank you for the best Zotero plugin for Obsidian ever!

I used the plugin before the new version (and name change) and it worked just fine for creating literature notes that doesn't have any annotations (like printed books I keep in Zotero for citation purposes). But now I can't create a note.

I open "Open quick switcher for literature notes"
I choose the citation
I get the messeage: "no attachment found for this file"

Other PDFs that doesn't yet have annotations just doesn't open or say any thing in the pop-up.

Thank you for the help!

**Comment by Kullenej** [comment]
It is working again! Thanks!!

**Comment by RyotaUshio** [comment]
I have the same issue. Could you reopen this issue?

Steps to reproduce:

1. Import an item from Google Scholar using Zotero connector (I followed [this instruction](https://guides.library.illinoisstate.edu/zotero/adding/googlescholar))
2. Now, the new item has no attachments or annotations. 
3. Inside the sandbox Obsidian vault, select "Link with Selected Literature" and choose the new item

https://github.com/PKM-er/obsidian-zotlit/assets/72342591/e93e5dfa-b7bb-45a3-b3a2-ae47f49eaa7c

```
SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 22.3.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Obsidian42 - BRAT v0.7.0
		2: ZotLit v1.1.0-beta.13

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by aidenlx** [comment]
@RyotaUshio your issue should be fixed in beta15

**Comment by RyotaUshio** [comment]
@aidenlx Just confirmed that it works perfectly! Thank you so much for your work:)
