### ISSUE TITLE
Issues with copy 

### ISSUE THREAD

**Issue by JustinStrat** [PKM-er/obsidian-zotlit#187]
I'm having the same issue others have reported with images not being created when using copy. Windows 11, Zotero 6, Zotlit beta-12. 
![image](https://github.com/PKM-er/obsidian-zotlit/assets/144282074/8a04f7a2-90b3-4773-a30d-f97a28a4100b)

**Comment by aidenlx** [comment]
could you check your console if there is any error?

**Comment by JustinStrat** [comment]
Looks like I'm running into a problem when the plugin loads at startup. 

![image](https://github.com/PKM-er/obsidian-zotlit/assets/144282074/d140c7d9-d70f-402a-ba0b-885b0acd38f5)

**Comment by aidenlx** [comment]
This is a known issue and should not be related to this. Any other error while you’re importing note?

**Comment by JustinStrat** [comment]
No there are no more errors. The files aren't created in the ZtImgExceprt however I can see them in the annotation panel.

**Comment by JustinStrat** [comment]
Yes! It may be a few days before I get back to you though.

**Comment by JustinStrat** [comment]
I managed to get to it today. Same problem in the sandbox with default templates and only zotlit and BRAT installed.

**Comment by aidenlx** [comment]
May I ask where do you store your Zotero data, default location or some external drive, or maybe onedrive?

**Comment by JustinStrat** [comment]
user/USERNAME/Zotero on both my PC and laptop. I should have mentioned I have this problem on both machines.

**Comment by aidenlx** [comment]
could you test if it's fixed in beta14? feel free to reopen this issue if it's still broken

**Comment by JustinStrat** [comment]
Fixed! Thanks for you hard work!
