### ISSUE TITLE
【Seeking help】Can't import images excerpt

### ISSUE THREAD

**Issue by iLern** [PKM-er/obsidian-zotlit#190]
**OS:** macOS Sonoma 14.0 (23A344)
**Zotero:** 6.0.27
**Obsidian Zotlit:**  1.1.0-beta.10
**Obsidian Note for Zotero:** 1.0.1

---

Same as issue #145 
<img width="723" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/43905872/f01eb37b-26c5-498f-9fd1-fcdcf07fa312">

I've configured the plugin as follows:
<img width="824" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/43905872/65d820e0-b80f-4aa0-b654-c039f7f6a561">
The 'attachments' folder is located in my Vault.

However, I **can** see the image in the side panel. Does this mean that the plugin should have created a symlink from Zotero cache but didn't succeed?
<img width="394" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/43905872/3ffbb3eb-4553-41cc-94c9-e5b32abc77c8">

Thanks a lot :)

**Comment by aidenlx** [comment]
should be fixed in beta14
