### ISSUE TITLE
Installation on Obsidian v1.4.14

### ISSUE THREAD

**Issue by hywang01** [PKM-er/obsidian-zotlit#194]
Hi there,

Many thanks for your contribution! My current version of Obsidian is v1.4.14, but I cannot find ZotLit in the plugin market.
I wonder how to install it?

Best,

hy

**Comment by Jarartur** [comment]
Hi, currently, you need to install it manually or by using another plugin called BRATS. It's described [here](https://zotlit.aidenlx.top/getting-started/install/obsidian).
