### ISSUE TITLE
Support html and epub annotations 

### ISSUE THREAD

**Issue by bepolymathe** [PKM-er/obsidian-zotlit#195]
Hi @aidenlx 

Thanks for your super work on this project. 
I don't know if I've missed something in the configuration, but I can't get annotations for html and epub pages, which are now annotatable with the latest version 7 of Zotero. Is this already implemented?

**Comment by aidenlx** [comment]
It hasn't been tested yet. If Zotero treat all attachment with annotation the same way, it might only need small adjustment to support. Anyway, stay tuned!

**Comment by aidenlx** [comment]
supported in v1.1.1
