### ISSUE TITLE
Two similar plugins appear

### ISSUE THREAD

**Issue by QiguaiR** [PKM-er/obsidian-zotlit#196]
When I replaced my old laptop with a new one, I copied the "plugins" folder from the original vault on the old laptop. As a result, two similar plugins appeared simultaneously on the new laptop:

![image](https://github.com/PKM-er/obsidian-zotlit/assets/128595110/3df636b9-4870-4c52-9545-801837826bfd)

However, prior to changing laptops, there was only one plugin called "Zotero Plugin," without the "ZotLit" plugin. I am unsure about the purpose of this new plugin and whether it functions similarly to the previous one. What should I do in this situation? Should I delete either the new or old plugin, or keep both?

**Comment by aidenlx** [comment]
You can keep only the newer "ZotLit" plugin and remove the old one. They are the same plugin. During the plugin review it's renamed to fit the requirements for third-party plugin. And if you are migrating from the earlier version better double check your settings to make sure are working as expected.
