### ISSUE TITLE
设置页面消失

### ISSUE THREAD

**Issue by lszddz** [PKM-er/obsidian-zotlit#197]
如图，最新1.10版本，从商店安装后设置里什么都没有。
<img width="1009" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/62652085/331dd314-40db-41f1-ba66-36611d58096e">

**Comment by aidenlx** [comment]
在最新版中无法复现，你看看新开一个库有没这个问题？

**Comment by lszddz** [comment]
新开了库依然是这样：<img width="1028" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/62652085/f0d46cc3-c421-4f9c-952a-9202ed746279">

**Comment by lszddz** [comment]
电脑是m1 pro macbook pro，系统是macos sonoma 14.0，obsidian版本是v1.4.14，zotlit版本是1.10

**Comment by aidenlx** [comment]
看下控制台有没报错？

**Comment by lszddz** [comment]
什么都没报，我也很诧异。之前用brat安装的，一直报错无法渲染yaml，我就删除进商店重新安装，就这样了。

**Comment by 1071189147** [comment]
同样，win10, Obsidian ZotLit

**Comment by aidenlx** [comment]
1.1.2应该可以了
