### ISSUE TITLE
Blank screen in Obsidian

### ISSUE THREAD

**Issue by heymaad** [PKM-er/obsidian-zotlit#199]
Installed the plugin through Obsidian store, and installed the better-sqlite3 as well. However, the plugin settings show a blank screen in Obsidian:
![image](https://github.com/PKM-er/obsidian-zotlit/assets/29626468/0518a0a7-aad7-487e-9f7d-5be568c2cc81)

**Comment by aidenlx** [comment]
should be fixed in 1.1.2
