### ISSUE TITLE
date data only has year value AND there is no funtions for formating dates.

### ISSUE THREAD

**Issue by ertugruluyar-github** [PKM-er/obsidian-zotlit#204]
![image](https://github.com/PKM-er/obsidian-zotlit/assets/70096810/b9a1f2fe-e496-4dbb-8bac-2f5f0aa27f77)

**Comment by aidenlx** [comment]
Duplicate of #202, could you post the link to the literature that have broken date? （post the follow-up in #202)

**Comment by aidenlx** [comment]
Oh and about formatting, you can use [moment](https://momentjs.com) to do date and time formatting

**Comment by ertugruluyar-github** [comment]
> Oh and about formatting, you can use [moment](https://momentjs.com) to do date and time formatting

Thanks.

**Comment by ParkerRobb** [comment]
See #265 for a workaround
