### ISSUE TITLE
Citation suggester不支持中文检索词

### ISSUE THREAD

**Issue by fsafsafs** [PKM-er/obsidian-zotlit#222]
如题，使用过程中发现无法搜索到中文文献，是否是插件目前不支持，或者我操作有误。图片上传一直失败。。总之我以中文标题名或作者名均不可。

**Comment by fsafsafs** [comment]
进一步使用，发现如果采用ctrl+p的命令，可以用中文检索。之前使用的是键入[@的方式，此时无法以中文检索。

**Comment by aidenlx** [comment]
1.1.4修复了
