### ISSUE TITLE
better-bibtext-search.sqlite not load

### ISSUE THREAD

**Issue by aiyolo** [PKM-er/obsidian-zotlit#243]
I installed  better-bibtext in zotero, but the plugin only generates better-bibtext.sqlite, and the better-bibtext-search.sqlite is missing.

![image](https://github.com/PKM-er/obsidian-zotlit/assets/12464091/621df148-d903-44fa-a546-f78a5f4a0c64)
zotero: 7.0.0-beta.47+f012a348a (64-bit)
obsidian: v1.4.16

how to configure it?

**Comment by FeralFlora** [comment]
This is a duplicate of #236. Follow the progress on solving this there.

**Comment by aidenlx** [comment]
should be fixed in v1.1.3
