### ISSUE TITLE
[Error] 无法加载注释面板

### ISSUE THREAD

**Issue by ucasyfp** [PKM-er/obsidian-zotlit#244]
只有在刚打开 obsidian 的一瞬间能加载出注释面板,之后换到任意一个 lecturenote都无法加载出注释面板. obsidian,插件版本都是最新. console 显示的错误命令:
<img width="548" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/49231020/2ff59ccf-d365-4901-a66f-3bfbb0633f6a">

**Comment by aidenlx** [comment]
你看看1.1.3有没修复，可能是better bibtex兼容的问题

**Comment by ucasyfp** [comment]
> 你看看1.1.3有没修复，可能是better bibtex兼容的问题
还是不行,插件好像会卡死,在 obsidian 的插件设置界面里都点击不了 tab
<img width="551" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/49231020/39d35d6f-bbda-42bf-ab2d-113532a1f1fd">

**Comment by aidenlx** [comment]
你看开个新库有这问题吗

**Comment by ucasyfp** [comment]
> 你看开个新库有这问题吗

好像还是不行,错误和上面差不多
<img width="540" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/49231020/cf2c60d2-faf7-429b-924f-29f928c703fa">

**Comment by ucasyfp** [comment]
> 你是用zotero 7吗，有用新加入的划线注释一类的吗

是的,用的是 zotero7,没有用过划线注释. 另外我刚刚在 mac 中新建了一个账户,在新账户中测试了一下只装了 zotlit 的obsidian,然后在 zotero 中加入了少量文献,使用起来没有出现上面的问题. 可能是我的 zotero的数据库有点问题吧, 我不知道该如何解决了.

(但发现了一个新的 bug,有时候关闭 obsidian 后重新打开会一直停在 loading 界面, 好像是.obsidian文件夹中 workspace.json文件的问题,只要我把这个文件删了再打开 obsidian 就能重新正常打开了.)

**Comment by aidenlx** [comment]
检查一下1.1.4有修复吗，没有的话再把issue重新开起来
