### ISSUE TITLE
Not picking up citekey from Zotero when creating literature note

### ISSUE THREAD

**Issue by docsez** [PKM-er/obsidian-zotlit#245]
Hi

When I 'Create literature note' from Zotero the note filename is not correct.  
The filename format is `<%= it.citekey ?? it.DOI ?? it.title ?? it.key %>.md` and the citekey is not being picked up.  I have the citekey in my properties template too - it's not picked up there either.
I am using Zotero 7.0.0-beta.47+f012a348a and BetterBibtex 6.7.128 (rolled back to try for a temporary fix until Zotlit works with BetterBibtex latest).
Whilst searching for solutions I saw that the the BetterBibtex database has moved - [link](https://github.com/retorquere/zotero-better-bibtex/issues/2684#issuecomment-1774151488)... and https://github.com/retorquere comments that the citation keys will move again in the future.  I love Zotlit *and* BetterBibtex, I just really want them to keep working together!

**Comment by aidenlx** [comment]
could you test if v1.1.3 fix this issue?

**Comment by docsez** [comment]
Fabulous, thank you, it works perfectly!
