### ISSUE TITLE
create literature note(s)无反应

### ISSUE THREAD

**Issue by CaoKang-David** [PKM-er/obsidian-zotlit#261]
在zotero中选中条目，右键点击它obsidian actions — create literature note(s)，能跳转到obsidian，弹出一个对话框让我选择pdf文档，选择以后，就没有反应，也没有弹出任何消息对话框。

**Comment by Emily-one** [comment]
我也是同样的问题，怎么解决？

**Comment by disheng2017** [comment]
在zotero中选中条目，右键点击它obsidian actions — create literature note(s)无反应，想请教下如何解决

**Comment by XYLisaZhang** [comment]
我也遇到了同样的问题
