### ISSUE TITLE
点击Create Literature Note(s)无法生成笔记，含调试日志

### ISSUE THREAD

**Issue by lc52520** [PKM-er/obsidian-zotlit#273]
一、软件情况
操作系统：Windows 10
Obsidian版本：1.4.16
    Zotlit：1.1.4
Zotero版本：6.0.30
    Better BibTex for Zotero：6.7.140
    Obsidian Note for Zotero：1.0.1
二、配置情况
![1702431790767](https://github.com/PKM-er/obsidian-zotlit/assets/4829046/d64894f0-a27a-43b1-9497-9d8cd782085e)
![1702431890893](https://github.com/PKM-er/obsidian-zotlit/assets/4829046/4165595a-0b6f-48b3-a1c2-e216bdde4427)
三、问题及现象
在Zotero中选中pdf，点击“Create Literature Note(s)”无法生成笔记
Obsidian控制台报错
![1702432075465](https://github.com/PKM-er/obsidian-zotlit/assets/4829046/11cef9ed-484e-428f-9a40-5991997fa176)

**Comment by lc52520** [comment]
自己弄好了

**Comment by 2455DD** [comment]
请问如何解决的

**Comment by docsez** [comment]
Me too please.  I have the same problem and can't work out how to fix it.

**Comment by SimLif** [comment]
这个错误主要由于引用了未定义变量的属性或方法造成，可以通过加?解决，如：it.date.first() -> it.date?.first()

**Comment by yangyanch** [comment]
> Obsidian控制台

老哥，请问怎么解决？

**Comment by playlove1900-collab** [comment]
同样的问题，请问是怎么解决的呢？
