### ISSUE TITLE
[Bug report] 无法正确显示callout的颜色 

### ISSUE THREAD

**Issue by iLern** [PKM-er/obsidian-zotlit#295]
## 问题描述
我根据[文档](https://zotlit.aidenlx.top/zh-CN/getting-started/basic-usage/template-config)修改了模板。然而，在重新更新笔记后（通过Force update by over writting），发现annotation并没有显示相应的颜色。虽然可以看到生成的文档内容已经改变，但似乎没有读取到`zt-colored.eta`。我想知道是否还需要进行额外设置。

## 环境信息
Obsidian v1.5.3
ZotLit  v1.1.4

## 附图
<img width="733" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/43905872/34e40fbe-d11c-4247-89e1-67f95be77be2">

<img width="405" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/43905872/41b1df06-6cd0-4e8a-951d-59d9d32033c5">

## 模板文件
```eta
// zt-colored.eta

<mark style="
<%- if (it.color) { _%> color: <%= it.color %>; <%_ } -%>
<%- if (it.bgColor) { _%> background-color: <%= it.bgColor %>; <%_ } -%>
"><%= it.content %></mark>
```

```eta
// zt-annot.eta

[!<%= it.colorName %>] Page <%= it.pageLabel %>

<%= it.imgEmbed %><%= it.text %>
<% if (it.comment) { %>
---
<%= it.comment %>
<% } %>
```

**Comment by CatCodeMe** [comment]
在ob里单独手动配置这种自定义callout的颜色就可以了，要么用插件callout manager, 比如你示例里的green类型的callout, 这种不是ob支持的类型，就会用默认的蓝色。或者用css片段也可以。 zotero里通过zotero style插件可以拿到不同颜色笔记的rgb，都创建一遍就可以了
