### ISSUE TITLE
Failed to load plugin zotlit

### ISSUE THREAD

**Issue by Shidiq** [PKM-er/obsidian-zotlit#316]
I got error after install Obisdian 1.5.8:

`The electron (electron: 28.2.3, module version: 119) in current version of obsidian is newer than the one supported by installed zotlit, please update zotlit to the latest version`

![CleanShot 2024-02-23 at 13 07 52@2x](https://github.com/PKM-er/obsidian-zotlit/assets/23032122/22bff0e7-8c68-4d82-9ee2-7cddf4bd6dfe)

**Comment by fbe555** [comment]
I got the same error after updating from 1.5.3 to 1.5.8 using snap on ubuntu 23.10. I have reverted the update and everything is working under 1.5.3.
I am waiting for a bugfix from obsidian, so fingers crossed this gets fixed before then, so I can start updating again.
Really great plugin, that's really boosting my M.Sc. thesis workflow :muscle: - Thank you for doing great work

**Comment by families** [comment]
Me too

**Comment by families** [comment]
Me too

**Comment by Crayon112** [comment]
me too

**Comment by fbe555** [comment]
> > I got the same error after updating from 1.5.3 to 1.5.8 using snap on ubuntu 23.10. I have reverted the update and everything is working under 1.5.3.
> 
> Hi, did you talk about the 1.5.4 ?

I happened to be on 1.5.3 when i snap refreshed to 1.5.8, and then I used snap revert to go back to 1.5.3, so there might be a working version in between the two. I wouldn't know.

**Comment by exusiaiwei** [comment]
Well, according to the Obsidian changelog (https://obsidian.md/changelog/), in version 1.5.8, "The installer has been updated to Electron v28.2.3". So, I believe that this problem should only impact the version 1.5.8.

**Comment by Atreyu-94** [comment]
I'm facing the same issue with Obsidian 1.5.8. Has someone some workaround?

**Comment by fbe555** [comment]
> I'm facing the same issue with Obsidian 1.5.8. Has someone some workaround?

Not apart from rolling back the update and sticking with the old version of obsidian until the issue is mitigated🤷

**Comment by 3e9b** [comment]
same issue here

**Comment by wwjCMP** [comment]
same issue

**Comment by aidenlx** [comment]
supported in v1.1.5

**Comment by SR023** [comment]
When i first use ,log reported:

`Theelectron (electron:25.8.1,module version:116)in current version of obsidian is not supported by zotlit,please reinstall using latest obsidian installer (.exe/.dmg/...)from obsidian.md ` 

When I updated it, the log reported an error.

` The electron (electron:32.2.2,module version:128)in current version of obsidian is newer than the one supported by installed zotlit,please update zotlit to the latest version` 

When I rolled back the zotlit version to 1.1.5, the log reported the error again

` The electron (electron:32.2.2,module version:128)in current version of obsidian is newer than the one supported by installed zotlit,please update zotlit to the latest version` 

my obsidian version is 1.7.5, zotlit is 1.1.8

What should I do?

**Comment by LeonStaufer** [comment]
Thank you for your work @aidenlx .

This issue this persists for me. ZotFile is unable to load:
<img width="376" alt="Image" src="https://github.com/user-attachments/assets/b5d7feb5-efb2-428f-8b75-7cb06b05f924" />

Here is my system info. The only plugin installed is ZotLit 1.1.9. I have tried manual installs, previous versions (1.1.8 and 1.1.5) with no success.
```
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 24.1.0
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 0
```

**Comment by Guoaking** [comment]
@LeonStaufer  pls check this issues  https://github.com/PKM-er/obsidian-zotlit/issues/366 it worked for me
