### ISSUE TITLE
对高版本obsidian支持

### ISSUE THREAD

**Issue by Msrzhu** [PKM-er/obsidian-zotlit#322]
可以更新一下对1.58版本obsidian的支持吗

**Comment by wwjCMP** [comment]
同样

**Comment by hipedo** [comment]
同求同求

**Comment by GraysonSmith** [comment]
同样有需求

**Comment by xurunze90** [comment]
同求新版更新
<img width="223" alt="452" src="https://github.com/PKM-er/obsidian-zotlit/assets/141986659/b2b0f071-f14f-426e-8031-0187cb4087ef">

**Comment by ethanchengyu** [comment]
同求更新

**Comment by aidenlx** [comment]
1.1.5已更新
