### ISSUE TITLE
When I enabled this plugin, The obsidian window became blank.

### ISSUE THREAD

**Issue by neuromaancer** [PKM-er/obsidian-zotlit#325]
<img width="1470" alt="Screenshot 2024-03-24 at 14 02 49" src="https://github.com/PKM-er/obsidian-zotlit/assets/28112871/16910354-aa48-4734-bda5-3d126f824b55">
Like this. I can't even start the developer tools. My obsidian version is:
<img width="653" alt="image" src="https://github.com/PKM-er/obsidian-zotlit/assets/28112871/16bf8c7e-1540-47ff-aa4f-c32de07cbd5f">

**Comment by Zsbyqx20** [comment]
Same for me.

**Comment by DualitysDance** [comment]
Me too. Maybe the newest obsidian version caused this bug.

**Comment by jiangxue000** [comment]
Me too. I tried version 1.3.7. It works

**Comment by MarionLaw** [comment]
Thank God, after seeing this issue, I tried to solve this problem, and now I have succeeded. The problem may be on the baseband version of v1.5.3. Delete (or overwrite the installation) v1.5.3 and reinstall the latest v1.5.11, and the problem will be solved.

**Comment by neuromaancer** [comment]
> Thank God, after seeing this issue, I tried to solve this problem, and now I have succeeded. The problem may be on the baseband version of v1.5.3. Delete (or overwrite the installation) v1.5.3 and reinstall the latest v1.5.11, and the problem will be solved.

It works! Thanks!
