### ISSUE TITLE
[BUG} Zotlit Plugin Black Screens Obsidian

### ISSUE THREAD

**Issue by ianTevesAcc** [PKM-er/obsidian-zotlit#360]
When Zotlit is enabled. It black screens Obsidian. This happened after installing the latest SQL3 Lite which was auto installed by Zotlit.

To make Obsidian function again. I had to disable Zotlit, but because of the black screen, I had to delete the plugin from the Obsidian plugins folder instead.

**Steps to reproduce:**
1. Install OB Zotlit plugin and enable.
2. Have the latest version of SQL Lite 3 either by...
    - following the instructions of Zotlit prompt window
    - automatically via the Zotlit prompt windows
    - manually by going through the docs.
3. Black screen occurs.

**System:**
OS: Windows 11 [64-bit]
OS build: 26120.1252
Version: 24H2
OB Version: v1.4.13
Zotlit Version: 1.1.6

**Video of Bug  + Solution:**
![record_2024-07-21_01-30-17](https://github.com/user-attachments/assets/b5a6ee98-707e-4dfd-8154-5febf752b6fc)

**Comment by ianTevesAcc** [comment]
I don't know if I did it correctly but I deleted SQL Lite 3 from my machine in order to solve the problem. But it still black screens.

So the problem persists with a clean install and a clean vault even without SQL Lite 3. Only if I did successfully deleted SQL from my machine.

**Comment by ianTevesAcc** [comment]
The issue doesn't appear in release v1.1.5

If you're having the same problem. I suggest you install that version until a fix is pushed.

**Comment by ianTevesAcc** [comment]
@aidenlx Sorry about that
I mentioned the installer version instead of the Obsidian version
OB Version: v1.6.7

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.13
	Operating system: Windows 10 Home 10.0.26120
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 0

RECOMMENDATIONS:
	none

**Comment by daeh** [comment]
Same issue. Updated the plugin, let it install `better-sqlite3` in its preferred way. Now Obsidian launches with a black screen and is unresponsive.

Obsidian v1.6.7
MacOS 14.5

**Comment by daeh** [comment]
(replacing `main.js`, `manifest.json`, `styles.css` with the 1.1.5 versions allowed Obsidian to launch)

**Comment by ianTevesAcc** [comment]
#355 

Uninstalling current Obsidian and reinstalling with a fresh Obsidian installer fixed the issue for me. The current hypothesis is that the Obsidian Installer is too old / the plugin can't work with the Obsidian installer being that old, therefore creating the bug.

To fix this issue:
1. Uninstall Obsidian from system (back up your data)
2. Download OB Installer ( Get the newest Obsidian Installer Version here - [https://obsidian.md/download](https://obsidian.md/download))
3. Run and installer and follow instructions
4. Install Zotlit through Community Plugins
5. Install Better-SQL-3 as per Zotlit's prompt windows instructions (Either automatically or manually)
6. Edit Plugins settings
7. Run `Reload app without saving` from command line through `command key + p`
8. Enjoy your functioning Zotlit plugin.
