### ISSUE TITLE
Obsidian corrupted on MacOS

### ISSUE THREAD

**Issue by flmaximwang** [PKM-er/obsidian-zotlit#363]
After updating zotlit to 1.1.7, my Obsidian corrupted with nothing in the window. DevTools said
<img width="339" alt="image" src="https://github.com/user-attachments/assets/a9c6094d-40f0-4d2d-bdd9-5ff4de2c16ce">

When I rolled back to 1.1.5, this problem disappeared.

**Comment by flmaximwang** [comment]
However, I cannot use any functions after rolling back to 1.1.5. Besides, it seemed that I reinstalled better-sqlite after updating to 1.1.7.

**Comment by flmaximwang** [comment]
<img width="802" alt="image" src="https://github.com/user-attachments/assets/a708db47-1e08-4a25-8c2d-4b04afcbc97b">
I failed to load these libraries. Is it possible that there‘re some problems with my better-sqlite? I was forced to manually install the new version of better-sqlite when updating to 1.1.7.

**Comment by flmaximwang** [comment]
After reinstalling Obsidian, manually copying the better_sqlite3.node file to /User/my_name/Library/Application Support/obsidian and renaming it to better-sqlite3-11.1.2.node, everything went well

**Comment by Litt7e** [comment]
> After reinstalling Obsidian, manually copying the better_sqlite3.node file to /User/my_name/Library/Application Support/obsidian and renaming it to better-sqlite3-11.1.2.node, everything went well

This method works for me！
