### ISSUE TITLE
Documentation for templating options

### ISSUE THREAD

**Issue by HEmile** [PKM-er/obsidian-zotlit#77]
Hello,

I'd like to match the template I had for the Citations plugin. There, I used (among others) the list of authors, the abstract and the year of publication. However, I'm not sure how to get these in the current plugin.

**Comment by MichaTarlton** [comment]
My guess is that they might be the same as what you see in the betterbibtex .json file.

![image](https://user-images.githubusercontent.com/23247219/235449896-f5649e7f-0aae-4f62-a6f7-3b91b5c682cd.png)

**Comment by zhechenghu** [comment]
Sure. It's on the side panel. You can use this command to open it:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/100691508/236664854-3c202423-b814-4e39-87e9-10f20793843b.png">

BTW, if it shows "Active file is not literature note" and your active file is indeed a literature note, you can just click the link button on the panel and select "Follow active literature note". Then it will be normal.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/100691508/236664958-63c7e958-bf23-4ebc-bc99-8c2dcda51ea8.png">

**Comment by aidenlx** [comment]
Please check out new document for tutorial of templating: https://zotlit.aidenlx.top/getting-started/basic-usage/template-basics

**Comment by SisyphusSmile** [comment]
Using templates, how would I insert a full citation/bibliography entry? 

e.g. What if I wanted to include a callout at the top of the body of each note which includes a fully formatted bibliography entry, for reference? Is this possible through templates?

**Comment by l-konrad** [comment]
> Sure. It's on the side panel. You can use this command to open it:
> 
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/100691508/236664854-3c202423-b814-4e39-87e9-10f20793843b.png">
> 
> BTW, if it shows "Active file is not literature note" and your active file is indeed a literature note, you can just click the link button on the panel and select "Follow active literature note". Then it will be normal.
> 
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/100691508/236664958-63c7e958-bf23-4ebc-bc99-8c2dcda51ea8.png">
> 
> @Rui0x


@zhechenghu 
hey this didnt work for me, i opened following issue: https://github.com/PKM-er/obsidian-zotlit/issues/445

any idea why it wouldn't work?
