### ISSUE TITLE
Feature: sync imported annotations with zotero

### ISSUE THREAD

**Issue by lkhphuc** [PKM-er/obsidian-zotlit#87]
Since in the document overview " Keep your annotation up-to-date with Zotero.", I will file this as a bug report, possibly include #49 

The annotation view sync intanstantly with zotero for new/changed comments, tags and image excerpt, but the annotation in the note is not updated, even when manually drag and drop the new updated block from annotation view to the md file

**Comment by pavlohrab** [comment]
I have the same issue. But, on my side, I can manually drag and drop them

**Comment by aidenlx** [comment]
in version v1.0.0, you can choose update note in `more options` to append new annotations and update frontmatter (better check on new note created in latest plugin first), I'll keep this issue open before the document is update accordingly.
